name: Web API Deploy Pipeline
on:
  push:
    paths:
      - ".github/workflows/**"
      - "cicd-section/api/**"

env:
  AWS_REGION: us-west-2
  ECS_CLUSTER: my-app-cluster
  ECS_SERVICE: my-app-api-service
  ECR_REPOSITORY: my-app-api
  ECS_TASK_DEFINITION_API: cicd-section/.aws/task-def-api.json

permissions:
  id-token: write
  contents: read

jobs:
  # test/build
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cicd-section/api
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Run tests and build an image
        run: docker image build -t temp_api_image:latest .
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      # ECRにログインする
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      # ECRに docker image をプッシュする
      - name: Push an image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker image tag temp_api_image:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker image push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
  # Deploy
